name: open_in_editor
description: Quickly open a Flutter project in the requested editor for native code development
version: 0.1.0
homepage: https://github.com/Rexios80/open_in_editor

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  pub_update_checker: ^1.2.0

dev_dependencies:
  rexios_lints: ^4.0.0

executables:
  oie: open_in_editor
