name: open_in_editor
description: Quickly open a Flutter project in the requested editor (Android Studio, Xcode)
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  pub_update_checker: ^1.2.0

dev_dependencies:
  rexios_lints: ^4.0.0
