name: open_in_editor
description: Quickly open a Flutter project in the requested editor for native code development
version: 0.1.2
homepage: https://github.com/Rexios80/open_in_editor

environment:
  sdk: ^3.0.0

dependencies:
  ansicolor: ^2.0.1
  path: ^1.9.1
  pub_update_checker: ^1.2.0

dev_dependencies:
  rexios_lints: ^9.3.0

executables:
  oie: open_in_editor
